// Drive Train
// On this page
// Speed controller declaration
// Robot Drive
/**

package org.usfirst.frc.team5442.robot.subsystems;

import org.usfirst.frc.team5442.robot.RobotMap;
import org.usfirst.frc.team5442.robot.commands.TankDrive;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/*
 *
 /
public class DriveTrain extends Subsystem {
	Spark sparkController1 = RobotMap.dTSparkController1;
	Spark sparkController2 = RobotMap.dTSparkController2;
	Spark sparkController3 = RobotMap.dTSparkController3;
	Spark sparkController4 = RobotMap.dTSparkController4;
	Spark sparkController5 = RobotMap.dTSparkController5;
	Spark sparkController6 = RobotMap.dTSparkController6;

	private RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	setDefaultCommand(new TankDrive());
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }


	public void robotDrive(double sparkLeft, double sparkRight) {
		robotDrive.tankDrive(sparkLeft, sparkRight);
		// TODO Auto-generated method stub
		
	}
}
*/
